version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: PostgreSQL
      POSTGRES_USER: eam
      POSTGRES_PASSWORD: eam
    ports:
      - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local